# ✏️ Esercizi

Molti di questi esercizi contengono concetti e funzioni che non sono stati spiegati in precedenza. Pertanto, è più sensato cercare di comprendere la soluzione fornita dopo aver letto attentamente il testo dell'esercizio, anziché cercare di risolverlo senza consultare preventivamente la soluzione.

In [ ]:
import numpy as np

**Esercizio 1.** Creare un vettore di dimensione 10 i cui elementi sono tutti 0 tranne il quinto  che è 1.

In [2]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**Esercizio 2.** Creare un vettore con valori compresi tra 10 e 49.

In [3]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**Esercizio 3.** Invertire un vettore (il primo elemento diventa l'ultimo).

In [4]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


**Esercizio 4.** Trovare gli indici degli elementi non zero di [1, 2, 0, 0, 4, s0].

In [5]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)


(array([0, 1, 4]),)


**Esercizio 5.** Crearere un array 10x10 con valori casuali e trovare i valori minimo e massimo.

In [7]:
Z = np.random.random((10,10))
Z

array([[0.5685575 , 0.69636659, 0.64022512, 0.18048263, 0.13003005,
        0.26901371, 0.4772437 , 0.4769572 , 0.04804521, 0.23366172],
       [0.94429468, 0.30112589, 0.23197319, 0.07213835, 0.6956314 ,
        0.60531729, 0.85947968, 0.47405032, 0.86539985, 0.73246051],
       [0.45533952, 0.45685126, 0.04109035, 0.91367378, 0.5628784 ,
        0.6369554 , 0.12771523, 0.18070776, 0.10579391, 0.14564602],
       [0.49926189, 0.94587924, 0.33946577, 0.86154299, 0.58716885,
        0.5443769 , 0.29076241, 0.85826184, 0.64535182, 0.13931905],
       [0.78909508, 0.80907071, 0.0663825 , 0.94142796, 0.51658768,
        0.90763672, 0.71235046, 0.87174129, 0.57212519, 0.04660884],
       [0.56297718, 0.36683633, 0.12188508, 0.49030984, 0.79648651,
        0.80447808, 0.1576028 , 0.49134277, 0.42336382, 0.65374928],
       [0.28757164, 0.09383478, 0.18631261, 0.44401181, 0.71575746,
        0.51517201, 0.42200856, 0.32598885, 0.5825556 , 0.14620881],
       [0.79809551, 0.37781001, 0.6059387

In [8]:
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.014126219711838917 0.9458792375201415


**Esercizio 6.** Creare un vettore casuale di dimensione 30 e trovare il valore medio.

In [10]:
Z = np.random.random(30)
Z

array([0.21512521, 0.51578555, 0.31608444, 0.68072781, 0.24529922,
       0.98913366, 0.34217569, 0.06336222, 0.92569309, 0.58279927,
       0.49893157, 0.25473186, 0.2597414 , 0.57216762, 0.28774702,
       0.56549581, 0.42810302, 0.12181564, 0.84560182, 0.73731621,
       0.40034753, 0.33765781, 0.40942202, 0.19661314, 0.33597455,
       0.08904976, 0.15738579, 0.8653456 , 0.58520359, 0.43406823])

In [11]:
m = Z.mean()
print(m)

0.4419635384983452


**Esercizio 7.** Dato un array 1D, negare tutti gli elementi compresi tra 3 e 8, inplace.

In [12]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


**Esercizio 8.** Qual è l'output di `print(sum(range(5),-1))`? 

In [13]:
print(sum(range(5),-1))

9


**Esercizio 9.** Creare un vettore casuale di dimensione 10 e sostituire il valore massimo con 0.

In [16]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.55369039 0.         0.73596212 0.82615362 0.07627594 0.72269315
 0.79729252 0.87911747 0.88345883 0.24151695]


**Esercizio 10.** Trovare il valore più vicino (a uno scalare dato) in un vettore.

In [21]:
Z = np.arange(100)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
v = np.random.uniform(0, 100)
v

56.79171600223777

In [24]:
index = (np.abs(Z - v)).argmin()
print(Z[index])


57


**Esercizio 11.** Convertire tutti gli elementi di un array numpy da float a integer.

In [31]:
a = np.array([[2.5, 3.8, 1.5], [4.7, 2.9, 1.56]])

o = a.astype("int")

print(o)


[[2 3 1]
 [4 2 1]]


**Esercizio 12.** Convertire un array numpy binario (contenente solo 0 e 1) in un array numpy booleano.

In [32]:
a = np.array([[1, 0, 0], [1, 1, 1], [0, 0, 0]])

o = a.astype("bool")

print(o)


[[ True False False]
 [ True  True  True]
 [False False False]]


**Esercizio 13.** Unire orizzontalmente due array numpy aventi la stessa prima dimensione (cioè lo stesso numero di righe negli array 2D).

In [33]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])

a2 = np.array([[7, 8, 9], [10, 11, 12]])

o = np.hstack((a1, a2))

print(o)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


**Esercizio 14.** Dati due array numpy, estrarre gli indici in cui gli elementi nei due array corrispondono.

In [34]:
a = np.array([1, 2, 3, 4, 5])

b = np.array([1, 3, 2, 4, 5])

print(np.where(a == b))


(array([0, 3, 4]),)


**Esercizio 15.** Generare un array ripetendo un array più piccolo di 2 dimensioni 10 volte.

In [35]:
a = np.array([[1, 2, 3], [4, 5, 6]])

o = np.tile(a, 10)

print(o)


[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]


**Esercizio 16.** Generare un array 5x5 di interi casuali compresi tra 0 (incluso) e 10 (escluso).

In [36]:
np.random.seed(123)  # setting the seed

o = np.random.randint(0, 10, size=(5, 5))

print(o)


[[2 2 6 1 3]
 [9 6 1 0 1]
 [9 0 0 9 3]
 [4 0 0 4 1]
 [7 3 2 4 7]]


**Esercizio 17.** Verificare se uno qualsiasi degli elementi di un array dato è diverso da zero.

In [38]:
x = np.array([1, 0, 0, 0])
print(np.any(x))
x = np.array([0, 0, 0, 0])
print(np.any(x))


True
False


**Esercizio 18.** Creare un confronto elemento per elemento (uguale, uguale entro una tolleranza) di due array dati.

In [40]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(np.equal(x, y))
print(np.allclose(x, y))


[ True  True  True  True  True  True  True  True  True False]
True


**Esercizio 19.** Trovare i dati mancanti in un array dato.

In [42]:
nums = np.array([[3, 2, np.nan, 1], [10, 12, 10, 9], [5, np.nan, 1, np.nan]])
nums



array([[ 3.,  2., nan,  1.],
       [10., 12., 10.,  9.],
       [ 5., nan,  1., nan]])

In [43]:
print(np.isnan(nums))

[[False False  True False]
 [False False False False]
 [False  True False  True]]


**Esercizio 20.** Scrivi un programma NumPy per estrarre tutti i numeri da un array dato che sono inferiori e superiori ad un numero specificato.

In [44]:
nums = np.array([[5.54, 3.38, 7.99], [3.54, 4.38, 6.99], [1.54, 2.39, 9.29]])
n = 6
print(nums[nums < n])


[5.54 3.38 3.54 4.38 1.54 2.39]


**Esercizio 21.** Sostituire tutti i numeri in un array dato che sono uguali, minori e maggiori di un dato numero.

In [12]:
nums = np.array([[5.54, 3.38, 7.99], [3.54, 8.32, 6.99], [1.54, 2.39, 9.29]])
n = 8.32
r = 18.32
print(np.where(nums == n, r, nums))

[[ 5.54  3.38  7.99]
 [ 3.54 18.32  6.99]
 [ 1.54  2.39  9.29]]


In [13]:
print("\nReplace elements with of the said array which are less than", n, "with", r)
print(np.where(nums < n, r, nums))


Replace elements with of the said array which are less than 8.32 with 18.32
[[18.32 18.32 18.32]
 [18.32  8.32 18.32]
 [18.32 18.32  9.29]]


In [14]:
print("\nReplace elements with of the said array which are greater than", n, "with", r)
print(np.where(nums > n, r, nums))


Replace elements with of the said array which are greater than 8.32 with 18.32
[[ 5.54  3.38  7.99]
 [ 3.54  8.32  6.99]
 [ 1.54  2.39 18.32]]


**Esercizio 22.** Moltiplicare due array dati della stessa dimensione elemento per elemento.

In [46]:
nums1 = np.array([[2, 5, 2], [1, 5, 5]])
nums2 = np.array([[5, 3, 4], [3, 2, 5]])


[[10 15  8]
 [ 3 10 25]]


In [47]:
print(nums1)

[[2 5 2]
 [1 5 5]]


In [ ]:
print(nums2)

In [ ]:
print(np.multiply(nums1, nums2))