# ✏️ Esercizi

Molti di questi esercizi contengono concetti e funzioni che non sono stati spiegati in precedenza. Pertanto, è più sensato cercare di comprendere la soluzione fornita dopo aver letto attentamente il testo dell'esercizio, anziché cercare di risolverlo senza consultare preventivamente la soluzione.

In [1]:
import numpy as np

**Esercizio 1.** Creare un vettore di dimensione 10 i cui elementi sono tutti 0 tranne il quinto  che è 1.

In [2]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**Esercizio 2.** Creare un vettore con valori compresi tra 10 e 49.

In [3]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**Esercizio 3.** Invertire un vettore (il primo elemento diventa l'ultimo).

In [4]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


**Esercizio 4.** Trovare gli indici degli elementi non zero di [1, 2, 0, 0, 4, s0].

In [5]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)


(array([0, 1, 4]),)


**Esercizio 5.** Crearere un array 10x10 con valori casuali e trovare i valori minimo e massimo.

In [6]:
Z = np.random.random((10,10))
Z

array([[0.58027841, 0.53624459, 0.50891615, 0.03679926, 0.72722143,
        0.56433413, 0.99901909, 0.22788565, 0.39926554, 0.497727  ],
       [0.04285036, 0.06974659, 0.42225797, 0.2365352 , 0.55977344,
        0.87253592, 0.94054647, 0.40811136, 0.63567155, 0.81695909],
       [0.07455896, 0.18920922, 0.14999998, 0.76620052, 0.62221683,
        0.9978866 , 0.94399568, 0.06283313, 0.3526249 , 0.21459802],
       [0.06991718, 0.3702588 , 0.05002059, 0.03540036, 0.23492816,
        0.23318608, 0.36915664, 0.97611237, 0.03299923, 0.55210407],
       [0.6232296 , 0.60212632, 0.82972614, 0.28260873, 0.91323274,
        0.71657674, 0.39610446, 0.85551724, 0.36872318, 0.23657755],
       [0.02116015, 0.9929866 , 0.19901684, 0.28910395, 0.96689486,
        0.80281636, 0.5629149 , 0.90283628, 0.41483679, 0.08520004],
       [0.18816144, 0.23084634, 0.64418623, 0.62091545, 0.64941611,
        0.40751897, 0.89259752, 0.30818646, 0.56312845, 0.43524431],
       [0.70027667, 0.98540884, 0.0727650

In [7]:
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0211601533994894 0.9990190904496313


**Esercizio 6.** Creare un vettore casuale di dimensione 30 e trovare il valore medio.

In [8]:
Z = np.random.random(30)
Z

array([0.57892968, 0.61258635, 0.31900194, 0.46564244, 0.98723254,
       0.14451866, 0.64550035, 0.48147131, 0.41508904, 0.74237312,
       0.88314566, 0.44113987, 0.25977011, 0.7238943 , 0.2711148 ,
       0.81151776, 0.09296992, 0.32017679, 0.63327619, 0.04226181,
       0.29387326, 0.86706535, 0.27214253, 0.23228034, 0.58861686,
       0.02633656, 0.93625054, 0.30864936, 0.71160624, 0.58265389])

In [9]:
m = Z.mean()
print(m)

0.4897029191218004


**Esercizio 7.** Dato un array 1D, negare tutti gli elementi compresi tra 3 e 8, inplace.

In [10]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


**Esercizio 8.** Qual è l'output di `print(sum(range(5),-1))`? 

In [11]:
print(sum(range(5),-1))

9


**Esercizio 9.** Creare un vettore casuale di dimensione 10 e sostituire il valore massimo con 0.

In [12]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.28134497 0.18299443 0.2748583  0.3570523  0.34292971 0.25353689
 0.31167918 0.         0.05092611 0.25660249]


**Esercizio 10.** Trovare il valore più vicino (a uno scalare dato) in un vettore.

In [13]:
Z = np.arange(100)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
v = np.random.uniform(0, 100)
v

29.045620557863717

In [15]:
index = (np.abs(Z - v)).argmin()
print(Z[index])


29


**Esercizio 11.** Convertire tutti gli elementi di un array numpy da float a integer.

In [16]:
a = np.array([[2.5, 3.8, 1.5], [4.7, 2.9, 1.56]])

o = a.astype("int")

print(o)


[[2 3 1]
 [4 2 1]]


**Esercizio 12.** Convertire un array numpy binario (contenente solo 0 e 1) in un array numpy booleano.

In [17]:
a = np.array([[1, 0, 0], [1, 1, 1], [0, 0, 0]])

o = a.astype("bool")

print(o)


[[ True False False]
 [ True  True  True]
 [False False False]]


**Esercizio 13.** Unire orizzontalmente due array numpy aventi la stessa prima dimensione (cioè lo stesso numero di righe negli array 2D).

In [18]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])

a2 = np.array([[7, 8, 9], [10, 11, 12]])

o = np.hstack((a1, a2))

print(o)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


**Esercizio 14.** Dati due array numpy, estrarre gli indici in cui gli elementi nei due array corrispondono.

In [19]:
a = np.array([1, 2, 3, 4, 5])

b = np.array([1, 3, 2, 4, 5])

print(np.where(a == b))


(array([0, 3, 4]),)


**Esercizio 15.** Generare un array ripetendo un array più piccolo di 2 dimensioni 10 volte.

In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])

o = np.tile(a, 10)

print(o)


[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]


**Esercizio 16.** Generare un array 5x5 di interi casuali compresi tra 0 (incluso) e 10 (escluso).

In [21]:
np.random.seed(123)  # setting the seed

o = np.random.randint(0, 10, size=(5, 5))

print(o)


[[2 2 6 1 3]
 [9 6 1 0 1]
 [9 0 0 9 3]
 [4 0 0 4 1]
 [7 3 2 4 7]]


**Esercizio 17.** Verificare se uno qualsiasi degli elementi di un array dato è diverso da zero.

In [22]:
x = np.array([1, 0, 0, 0])
print(np.any(x))
x = np.array([0, 0, 0, 0])
print(np.any(x))


True
False


**Esercizio 18.** Creare un confronto elemento per elemento (uguale, uguale entro una tolleranza) di due array dati.

In [23]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(np.equal(x, y))
print(np.allclose(x, y))


[ True  True  True  True  True  True  True  True  True False]
True


**Esercizio 19.** Trovare i dati mancanti in un array dato.

In [24]:
nums = np.array([[3, 2, np.nan, 1], [10, 12, 10, 9], [5, np.nan, 1, np.nan]])
nums



array([[ 3.,  2., nan,  1.],
       [10., 12., 10.,  9.],
       [ 5., nan,  1., nan]])

In [25]:
print(np.isnan(nums))

[[False False  True False]
 [False False False False]
 [False  True False  True]]


**Esercizio 20.** Scrivi un programma NumPy per estrarre tutti i numeri da un array dato che sono inferiori e superiori ad un numero specificato.

In [26]:
nums = np.array([[5.54, 3.38, 7.99], [3.54, 4.38, 6.99], [1.54, 2.39, 9.29]])
n = 6
print(nums[nums < n])


[5.54 3.38 3.54 4.38 1.54 2.39]


**Esercizio 21.** Sostituire tutti i numeri in un array dato che sono uguali, minori e maggiori di un dato numero.

In [27]:
nums = np.array([[5.54, 3.38, 7.99], [3.54, 8.32, 6.99], [1.54, 2.39, 9.29]])
n = 8.32
r = 18.32
print(np.where(nums == n, r, nums))

[[ 5.54  3.38  7.99]
 [ 3.54 18.32  6.99]
 [ 1.54  2.39  9.29]]


In [28]:
print("\nReplace elements with of the said array which are less than", n, "with", r)
print(np.where(nums < n, r, nums))


Replace elements with of the said array which are less than 8.32 with 18.32
[[18.32 18.32 18.32]
 [18.32  8.32 18.32]
 [18.32 18.32  9.29]]


In [29]:
print("\nReplace elements with of the said array which are greater than", n, "with", r)
print(np.where(nums > n, r, nums))


Replace elements with of the said array which are greater than 8.32 with 18.32
[[ 5.54  3.38  7.99]
 [ 3.54  8.32  6.99]
 [ 1.54  2.39 18.32]]


**Esercizio 22.** Moltiplicare due array dati della stessa dimensione elemento per elemento.

In [30]:
nums1 = np.array([[2, 5, 2], [1, 5, 5]])
nums2 = np.array([[5, 3, 4], [3, 2, 5]])


In [31]:
print(nums1)

[[2 5 2]
 [1 5 5]]


In [32]:
print(nums2)

[[5 3 4]
 [3 2 5]]


In [33]:
print(np.multiply(nums1, nums2))

[[10 15  8]
 [ 3 10 25]]
