In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5, 6])

In [3]:
print(x)

[1 2 3 4 5 6]


In [4]:
x[0]

1

In [5]:
x[2]

3

In [6]:
y = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
y[0, 2]

3

In [8]:
y[1]

array([5, 6, 7, 8])

In [9]:
y[:, 1] 

array([ 2,  6, 10])

In [10]:
# Display the first row of the array
print("Displaying the first row:")
print(y[0, :])

Displaying the first row:
[1 2 3 4]


In [11]:
# Show the last two elements in the first row
print("Showing the last two elements in the first row:")
print(y[0, -2:])

Showing the last two elements in the first row:
[3 4]


In [12]:
# Retrieve every second element in the first row
print("Retrieving every second element in the first row:")
print(y[0, ::2])

Retrieving every second element in the first row:
[1 3]


In [13]:
# Extract a submatrix from the original array
print("Extracting a submatrix:")
print(y[:2, 1:3])

Extracting a submatrix:
[[2 3]
 [6 7]]


In [14]:
z = np.arange(2, 9, 2)
print(z)

[2 4 6 8]


In [15]:
w = np.arange(11)
print(w)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [16]:
x = np.linspace(0, 10, num=20)
print(x)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [17]:
print(x[x > 7])

[ 7.36842105  7.89473684  8.42105263  8.94736842  9.47368421 10.        ]


In [18]:
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
y.ndim

2

In [20]:
print(y.max(axis=1))

[ 4  8 12]


In [21]:
print(y.max(axis=0))

[ 9 10 11 12]


In [22]:
y.shape

(3, 4)

In [23]:
m = np.array([1.62, 1.75, 1.55, 1.74])
kg = np.array([55.4, 73.6, 57.1, 59.5])

print(m)
print(kg)

[1.62 1.75 1.55 1.74]
[55.4 73.6 57.1 59.5]


In [24]:
55.4 / 1.62**2

21.109586953208346

In [25]:
kg[0] / m[0]**2

21.109586953208346

In [26]:
bmi = kg / m**2

In [27]:
bmi.round(1)

array([21.1, 24. , 23.8, 19.7])

In [28]:
# Creiamo un array 3x3
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Definiamo uno scalare
B = 5

# Applichiamo il broadcasting per aggiungere lo scalare a ogni elemento dell'array
C = A + B

print(C)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [29]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [30]:
[x.min(), x.max(), x.sum(), x.mean(), x.std()]

[1, 3, 6, 2.0, 0.816496580927726]

In [31]:
print(x)

[1 2 3]


In [32]:
np.sqrt(np.sum((x - np.mean(x)) ** 2) / np.size(x))

0.816496580927726

In [33]:
np.mean(x)

2.0

In [34]:
x - np.mean(x)

array([-1.,  0.,  1.])

In [35]:
(x - np.mean(x)) ** 2

array([1., 0., 1.])

In [36]:
np.sum((x - np.mean(x)) ** 2)

2.0

In [37]:
res = np.sum((x - np.mean(x)) ** 2) / np.size(x)
res

0.6666666666666666

In [38]:
np.sqrt(res)

0.816496580927726

In [39]:
np.std(x)

0.816496580927726

In [40]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
y = x[:2, 1:3]
print(y)

[[2 3]
 [6 7]]


In [42]:
print(x[0, 1])   

2


In [43]:
y[0, 0] = 77     


In [44]:
print(x)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

z = x.copy()
print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
z[0, 1] = 33
print(z)

[[ 1 33  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [47]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [48]:
A = np.array([[1, 2], [3, 4]])

In [49]:
B = A

In [50]:
B[0,0] = 10

In [51]:
print(A)

[[10  2]
 [ 3  4]]


In [52]:
B = np.copy(A)

In [53]:
B[0,0] = -5

In [54]:
print(B)

[[-5  2]
 [ 3  4]]


In [55]:
print(A)

[[10  2]
 [ 3  4]]


In [56]:
%load_ext watermark
%watermark -n -u -v -iv -w -m

Last updated: Sun Jun 16 2024

Python implementation: CPython
Python version       : 3.12.3
IPython version      : 8.25.0

Compiler    : Clang 16.0.6 
OS          : Darwin
Release     : 23.4.0
Machine     : arm64
Processor   : arm
CPU cores   : 8
Architecture: 64bit

numpy: 1.26.4

Watermark: 2.4.3

