In [1]:
import numpy as np

In [2]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [5]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)


(array([0, 1, 4]),)


In [6]:
Z = np.random.random((10,10))
Z

array([[0.89981024, 0.41106322, 0.48236344, 0.9471851 , 0.92593789,
        0.53085606, 0.40899089, 0.20170546, 0.74914125, 0.00909079],
       [0.73476833, 0.54712533, 0.87181142, 0.05642964, 0.99968106,
        0.96019168, 0.66869119, 0.28170295, 0.89614843, 0.81592657],
       [0.39299397, 0.73926091, 0.14793839, 0.28845696, 0.1393458 ,
        0.25337854, 0.93881304, 0.0920264 , 0.10051206, 0.84065957],
       [0.0623416 , 0.78380244, 0.47378617, 0.7469547 , 0.62326339,
        0.15626906, 0.41268633, 0.56943408, 0.93728883, 0.38872961],
       [0.93608234, 0.3579921 , 0.47586337, 0.79575336, 0.67190579,
        0.29455014, 0.2931828 , 0.23772448, 0.87348951, 0.44500186],
       [0.38826595, 0.08054701, 0.73772039, 0.68084949, 0.4960215 ,
        0.70114679, 0.67331352, 0.16287816, 0.54226544, 0.58421688],
       [0.06852491, 0.5620969 , 0.38148111, 0.32014225, 0.09508479,
        0.87432138, 0.70029218, 0.43070282, 0.85991159, 0.23394308],
       [0.9373202 , 0.47391665, 0.3640702

In [7]:
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00909078553377296 0.9996810564629426


In [8]:
Z = np.random.random(30)
Z

array([0.83225127, 0.98340948, 0.66253475, 0.89537726, 0.57619638,
       0.91205395, 0.89843678, 0.09767406, 0.6744062 , 0.59859476,
       0.73358925, 0.87420413, 0.93501225, 0.30244071, 0.13022122,
       0.19018332, 0.76350228, 0.32526676, 0.0344072 , 0.41083451,
       0.63249139, 0.65637149, 0.24915358, 0.21082056, 0.64720005,
       0.52699554, 0.25698453, 0.75575132, 0.54750125, 0.59027421])

In [9]:
m = Z.mean()
print(m)

0.5634713471977558


In [10]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [11]:
print(sum(range(5),-1))

9


In [12]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.57396299 0.         0.32794042 0.70965358 0.21765236 0.3713405
 0.69776482 0.36518699 0.15709115 0.28395666]


In [13]:
Z = np.arange(100)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
v = np.random.uniform(0, 100)
v

47.615399402458756

In [15]:
index = (np.abs(Z - v)).argmin()
print(Z[index])


48


In [16]:
a = np.array([[2.5, 3.8, 1.5], [4.7, 2.9, 1.56]])

o = a.astype("int")

print(o)


[[2 3 1]
 [4 2 1]]


In [17]:
a = np.array([[1, 0, 0], [1, 1, 1], [0, 0, 0]])

o = a.astype("bool")

print(o)


[[ True False False]
 [ True  True  True]
 [False False False]]


In [18]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])

a2 = np.array([[7, 8, 9], [10, 11, 12]])

o = np.hstack((a1, a2))

print(o)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [19]:
a = np.array([1, 2, 3, 4, 5])

b = np.array([1, 3, 2, 4, 5])

print(np.where(a == b))


(array([0, 3, 4]),)


In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])

o = np.tile(a, 10)

print(o)


[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]


In [21]:
np.random.seed(123)  # setting the seed

o = np.random.randint(0, 10, size=(5, 5))

print(o)


[[2 2 6 1 3]
 [9 6 1 0 1]
 [9 0 0 9 3]
 [4 0 0 4 1]
 [7 3 2 4 7]]


In [22]:
x = np.array([1, 0, 0, 0])
print(np.any(x))
x = np.array([0, 0, 0, 0])
print(np.any(x))


True
False


In [23]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(np.equal(x, y))
print(np.allclose(x, y))


[ True  True  True  True  True  True  True  True  True False]
True


In [24]:
nums = np.array([[3, 2, np.nan, 1], [10, 12, 10, 9], [5, np.nan, 1, np.nan]])
nums



array([[ 3.,  2., nan,  1.],
       [10., 12., 10.,  9.],
       [ 5., nan,  1., nan]])

In [25]:
print(np.isnan(nums))

[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [26]:
nums = np.array([[5.54, 3.38, 7.99], [3.54, 4.38, 6.99], [1.54, 2.39, 9.29]])
n = 6
print(nums[nums < n])


[5.54 3.38 3.54 4.38 1.54 2.39]


In [27]:
nums = np.array([[5.54, 3.38, 7.99], [3.54, 8.32, 6.99], [1.54, 2.39, 9.29]])
n = 8.32
r = 18.32
print(np.where(nums == n, r, nums))

[[ 5.54  3.38  7.99]
 [ 3.54 18.32  6.99]
 [ 1.54  2.39  9.29]]


In [28]:
print("\nReplace elements with of the said array which are less than", n, "with", r)
print(np.where(nums < n, r, nums))


Replace elements with of the said array which are less than 8.32 with 18.32
[[18.32 18.32 18.32]
 [18.32  8.32 18.32]
 [18.32 18.32  9.29]]


In [29]:
print("\nReplace elements with of the said array which are greater than", n, "with", r)
print(np.where(nums > n, r, nums))


Replace elements with of the said array which are greater than 8.32 with 18.32
[[ 5.54  3.38  7.99]
 [ 3.54  8.32  6.99]
 [ 1.54  2.39 18.32]]


In [30]:
nums1 = np.array([[2, 5, 2], [1, 5, 5]])
nums2 = np.array([[5, 3, 4], [3, 2, 5]])


In [31]:
print(nums1)

[[2 5 2]
 [1 5 5]]


In [32]:
print(nums2)

[[5 3 4]
 [3 2 5]]


In [33]:
print(np.multiply(nums1, nums2))

[[10 15  8]
 [ 3 10 25]]
