In [1]:
import numpy as np

In [2]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [5]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)


(array([0, 1, 4]),)


In [6]:
Z = np.random.random((10,10))
Z

array([[3.48809163e-01, 2.66595076e-01, 2.52944156e-01, 6.16420971e-01,
        7.02449597e-01, 5.70511547e-03, 3.34401818e-01, 5.79128571e-01,
        6.48625823e-01, 9.71815978e-02],
       [2.48893777e-01, 2.53892688e-01, 9.04497154e-01, 6.15440783e-01,
        2.72155541e-01, 6.48818506e-01, 1.68872394e-01, 5.20181055e-01,
        9.83715889e-01, 4.97634937e-01],
       [7.39169698e-01, 5.44546028e-01, 9.65193475e-01, 1.83544017e-01,
        4.40874726e-01, 9.79371961e-01, 1.85931490e-01, 3.70557948e-01,
        4.70657744e-01, 3.15267326e-01],
       [6.13244525e-01, 6.48263987e-01, 3.94923048e-01, 2.44805403e-01,
        4.27280268e-01, 6.39645660e-01, 1.63134302e-01, 1.94513994e-01,
        8.58020286e-02, 6.08294612e-01],
       [4.93866883e-02, 4.81633993e-01, 3.69982420e-01, 1.98549754e-01,
        6.78523670e-01, 3.44549801e-01, 6.09230793e-01, 4.90131117e-01,
        2.33428558e-01, 4.62013532e-01],
       [8.35310952e-01, 2.91465590e-01, 5.06807892e-01, 4.15620804e-01,
   

In [7]:
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0004896324895068416 0.9837158892487576


In [8]:
Z = np.random.random(30)
Z

array([0.39674173, 0.42053271, 0.4419196 , 0.37080346, 0.6358649 ,
       0.65889823, 0.86589929, 0.68550684, 0.28964707, 0.78163662,
       0.79163728, 0.01452091, 0.42502257, 0.20000721, 0.98854815,
       0.62911687, 0.11984633, 0.23472834, 0.15432729, 0.26662233,
       0.79120053, 0.34772388, 0.84564513, 0.94284222, 0.19700974,
       0.33474636, 0.27418989, 0.41070268, 0.23446756, 0.80739441])

In [9]:
m = Z.mean()
print(m)

0.48525833838833127


In [10]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [11]:
print(sum(range(5),-1))

9


In [12]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.55136846 0.30809578 0.12143684 0.01400652 0.6903808  0.75372618
 0.46475871 0.43568575 0.2754191  0.        ]


In [13]:
Z = np.arange(100)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
v = np.random.uniform(0, 100)
v

90.10323605719698

In [15]:
index = (np.abs(Z - v)).argmin()
print(Z[index])


90


In [16]:
a = np.array([[2.5, 3.8, 1.5], [4.7, 2.9, 1.56]])

o = a.astype("int")

print(o)


[[2 3 1]
 [4 2 1]]


In [17]:
a = np.array([[1, 0, 0], [1, 1, 1], [0, 0, 0]])

o = a.astype("bool")

print(o)


[[ True False False]
 [ True  True  True]
 [False False False]]


In [18]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])

a2 = np.array([[7, 8, 9], [10, 11, 12]])

o = np.hstack((a1, a2))

print(o)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [19]:
a = np.array([1, 2, 3, 4, 5])

b = np.array([1, 3, 2, 4, 5])

print(np.where(a == b))


(array([0, 3, 4]),)


In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])

o = np.tile(a, 10)

print(o)


[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]


In [21]:
np.random.seed(123)  # setting the seed

o = np.random.randint(0, 10, size=(5, 5))

print(o)


[[2 2 6 1 3]
 [9 6 1 0 1]
 [9 0 0 9 3]
 [4 0 0 4 1]
 [7 3 2 4 7]]


In [22]:
x = np.array([1, 0, 0, 0])
print(np.any(x))
x = np.array([0, 0, 0, 0])
print(np.any(x))


True
False


In [23]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(np.equal(x, y))
print(np.allclose(x, y))


[ True  True  True  True  True  True  True  True  True False]
True


In [24]:
nums = np.array([[3, 2, np.nan, 1], [10, 12, 10, 9], [5, np.nan, 1, np.nan]])
nums



array([[ 3.,  2., nan,  1.],
       [10., 12., 10.,  9.],
       [ 5., nan,  1., nan]])

In [25]:
print(np.isnan(nums))

[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [26]:
nums = np.array([[5.54, 3.38, 7.99], [3.54, 4.38, 6.99], [1.54, 2.39, 9.29]])
n = 6
print(nums[nums < n])


[5.54 3.38 3.54 4.38 1.54 2.39]


In [27]:
nums = np.array([[5.54, 3.38, 7.99], [3.54, 8.32, 6.99], [1.54, 2.39, 9.29]])
n = 8.32
r = 18.32
print(np.where(nums == n, r, nums))

[[ 5.54  3.38  7.99]
 [ 3.54 18.32  6.99]
 [ 1.54  2.39  9.29]]


In [28]:
print("\nReplace elements with of the said array which are less than", n, "with", r)
print(np.where(nums < n, r, nums))


Replace elements with of the said array which are less than 8.32 with 18.32
[[18.32 18.32 18.32]
 [18.32  8.32 18.32]
 [18.32 18.32  9.29]]


In [29]:
print("\nReplace elements with of the said array which are greater than", n, "with", r)
print(np.where(nums > n, r, nums))


Replace elements with of the said array which are greater than 8.32 with 18.32
[[ 5.54  3.38  7.99]
 [ 3.54  8.32  6.99]
 [ 1.54  2.39 18.32]]


In [30]:
nums1 = np.array([[2, 5, 2], [1, 5, 5]])
nums2 = np.array([[5, 3, 4], [3, 2, 5]])


In [31]:
print(nums1)

[[2 5 2]
 [1 5 5]]


In [32]:
print(nums2)

[[5 3 4]
 [3 2 5]]


In [33]:
print(np.multiply(nums1, nums2))

[[10 15  8]
 [ 3 10 25]]
