In [1]:
import numpy as np

In [2]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [5]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)


(array([0, 1, 4]),)


In [6]:
Z = np.random.random((10,10))
Z

array([[0.52152729, 0.84254749, 0.68717497, 0.91529673, 0.83120451,
        0.75138463, 0.60886848, 0.49840418, 0.04055574, 0.81316018],
       [0.22910269, 0.38001207, 0.98398785, 0.26645289, 0.51233374,
        0.94441646, 0.12803707, 0.42020964, 0.98086854, 0.87820339],
       [0.03752557, 0.43066288, 0.16994054, 0.39932642, 0.29249879,
        0.76957226, 0.43825446, 0.47048975, 0.59700921, 0.05667934],
       [0.39576581, 0.46346237, 0.84767028, 0.35771971, 0.48885291,
        0.24930765, 0.25898443, 0.05104691, 0.62033401, 0.58476312],
       [0.27586987, 0.37117681, 0.32816074, 0.72987812, 0.42800015,
        0.81842844, 0.14726948, 0.39126805, 0.53727696, 0.72222774],
       [0.43158671, 0.91512172, 0.29204516, 0.77524293, 0.23038204,
        0.99787214, 0.93999789, 0.52254533, 0.71398363, 0.47530307],
       [0.50289326, 0.56940512, 0.82226543, 0.37127219, 0.05297079,
        0.06554668, 0.72268229, 0.58234891, 0.01670491, 0.59981142],
       [0.32980154, 0.36545866, 0.8711220

In [7]:
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.01670491143597297 0.997872137769451


In [8]:
Z = np.random.random(30)
Z

array([0.84290224, 0.24595771, 0.36961772, 0.80165815, 0.62289984,
       0.0523289 , 0.47119321, 0.18930412, 0.15814241, 0.0166162 ,
       0.52199196, 0.16015865, 0.23385923, 0.27966452, 0.82900955,
       0.63540811, 0.76438072, 0.15882049, 0.75870056, 0.43760991,
       0.37672344, 0.68617707, 0.45281649, 0.43057503, 0.54162427,
       0.5097832 , 0.92321847, 0.94378765, 0.82867463, 0.26148364])

In [9]:
m = Z.mean()
print(m)

0.48350293615444023


In [10]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [11]:
print(sum(range(5),-1))

9


In [12]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.7047905  0.03068113 0.         0.50655661 0.17158109 0.044924
 0.12150688 0.19021589 0.71976652 0.57995115]


In [13]:
Z = np.arange(100)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
v = np.random.uniform(0, 100)
v

49.41111063313882

In [15]:
index = (np.abs(Z - v)).argmin()
print(Z[index])


49


In [16]:
a = np.array([[2.5, 3.8, 1.5], [4.7, 2.9, 1.56]])

o = a.astype("int")

print(o)


[[2 3 1]
 [4 2 1]]


In [17]:
a = np.array([[1, 0, 0], [1, 1, 1], [0, 0, 0]])

o = a.astype("bool")

print(o)


[[ True False False]
 [ True  True  True]
 [False False False]]


In [18]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])

a2 = np.array([[7, 8, 9], [10, 11, 12]])

o = np.hstack((a1, a2))

print(o)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [19]:
a = np.array([1, 2, 3, 4, 5])

b = np.array([1, 3, 2, 4, 5])

print(np.where(a == b))


(array([0, 3, 4]),)


In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])

o = np.tile(a, 10)

print(o)


[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]


In [21]:
np.random.seed(123)  # setting the seed

o = np.random.randint(0, 10, size=(5, 5))

print(o)


[[2 2 6 1 3]
 [9 6 1 0 1]
 [9 0 0 9 3]
 [4 0 0 4 1]
 [7 3 2 4 7]]


In [22]:
x = np.array([1, 0, 0, 0])
print(np.any(x))
x = np.array([0, 0, 0, 0])
print(np.any(x))


True
False


In [23]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(np.equal(x, y))
print(np.allclose(x, y))


[ True  True  True  True  True  True  True  True  True False]
True


In [24]:
nums = np.array([[3, 2, np.nan, 1], [10, 12, 10, 9], [5, np.nan, 1, np.nan]])
nums



array([[ 3.,  2., nan,  1.],
       [10., 12., 10.,  9.],
       [ 5., nan,  1., nan]])

In [25]:
print(np.isnan(nums))

[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [26]:
nums = np.array([[5.54, 3.38, 7.99], [3.54, 4.38, 6.99], [1.54, 2.39, 9.29]])
n = 6
print(nums[nums < n])


[5.54 3.38 3.54 4.38 1.54 2.39]


In [27]:
nums = np.array([[5.54, 3.38, 7.99], [3.54, 8.32, 6.99], [1.54, 2.39, 9.29]])
n = 8.32
r = 18.32
print(np.where(nums == n, r, nums))

[[ 5.54  3.38  7.99]
 [ 3.54 18.32  6.99]
 [ 1.54  2.39  9.29]]


In [28]:
print("\nReplace elements with of the said array which are less than", n, "with", r)
print(np.where(nums < n, r, nums))


Replace elements with of the said array which are less than 8.32 with 18.32
[[18.32 18.32 18.32]
 [18.32  8.32 18.32]
 [18.32 18.32  9.29]]


In [29]:
print("\nReplace elements with of the said array which are greater than", n, "with", r)
print(np.where(nums > n, r, nums))


Replace elements with of the said array which are greater than 8.32 with 18.32
[[ 5.54  3.38  7.99]
 [ 3.54  8.32  6.99]
 [ 1.54  2.39 18.32]]


In [30]:
nums1 = np.array([[2, 5, 2], [1, 5, 5]])
nums2 = np.array([[5, 3, 4], [3, 2, 5]])


In [31]:
print(nums1)

[[2 5 2]
 [1 5 5]]


In [32]:
print(nums2)

[[5 3 4]
 [3 2 5]]


In [33]:
print(np.multiply(nums1, nums2))

[[10 15  8]
 [ 3 10 25]]
