In [1]:
import numpy as np

In [2]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [5]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)


(array([0, 1, 4]),)


In [6]:
Z = np.random.random((10,10))
Z

array([[0.52424342, 0.74353559, 0.75419585, 0.9830306 , 0.127273  ,
        0.53242061, 0.01094647, 0.99929536, 0.42000572, 0.36728521],
       [0.43254115, 0.42255648, 0.4205056 , 0.94852678, 0.92489078,
        0.07447573, 0.47419685, 0.7645669 , 0.62308967, 0.26821719],
       [0.44161824, 0.31564694, 0.56592866, 0.12633733, 0.49055132,
        0.30802898, 0.69725083, 0.50296239, 0.97864412, 0.22255457],
       [0.05760945, 0.51994889, 0.74574188, 0.56822555, 0.81790983,
        0.4520208 , 0.38148396, 0.78834824, 0.62576001, 0.37965603],
       [0.89438911, 0.48984206, 0.03688774, 0.63694522, 0.66940936,
        0.8199061 , 0.16624008, 0.6139922 , 0.32044358, 0.25021302],
       [0.16764662, 0.67708192, 0.59822945, 0.71734665, 0.75127621,
        0.02935947, 0.55306582, 0.6019979 , 0.50505386, 0.92774491],
       [0.53716795, 0.74869046, 0.04902159, 0.72936959, 0.54359216,
        0.93729708, 0.36347598, 0.05066142, 0.81358877, 0.61009454],
       [0.75813141, 0.17153557, 0.4546129

In [7]:
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.009662323990775046 0.9992953606752542


In [8]:
Z = np.random.random(30)
Z

array([0.82949977, 0.69993512, 0.61478815, 0.66027219, 0.60207705,
       0.38230888, 0.41140665, 0.82673378, 0.52811733, 0.21903071,
       0.16504487, 0.96586549, 0.29018818, 0.65976277, 0.17965431,
       0.88036505, 0.57582906, 0.35015733, 0.63341364, 0.95395948,
       0.36809354, 0.55104945, 0.70342544, 0.88897994, 0.90640909,
       0.10262751, 0.3458725 , 0.11883452, 0.04358312, 0.57070688])

In [9]:
m = Z.mean()
print(m)

0.5342663938303274


In [10]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [11]:
print(sum(range(5),-1))

9


In [12]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.46484895 0.48949361 0.         0.66229814 0.01921751 0.05736971
 0.10335721 0.15365263 0.05764812 0.0775173 ]


In [13]:
Z = np.arange(100)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
v = np.random.uniform(0, 100)
v

97.68546133148459

In [15]:
index = (np.abs(Z - v)).argmin()
print(Z[index])


98


In [16]:
a = np.array([[2.5, 3.8, 1.5], [4.7, 2.9, 1.56]])

o = a.astype("int")

print(o)


[[2 3 1]
 [4 2 1]]


In [17]:
a = np.array([[1, 0, 0], [1, 1, 1], [0, 0, 0]])

o = a.astype("bool")

print(o)


[[ True False False]
 [ True  True  True]
 [False False False]]


In [18]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])

a2 = np.array([[7, 8, 9], [10, 11, 12]])

o = np.hstack((a1, a2))

print(o)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [19]:
a = np.array([1, 2, 3, 4, 5])

b = np.array([1, 3, 2, 4, 5])

print(np.where(a == b))


(array([0, 3, 4]),)


In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])

o = np.tile(a, 10)

print(o)


[[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6 4 5 6]]


In [21]:
np.random.seed(123)  # setting the seed

o = np.random.randint(0, 10, size=(5, 5))

print(o)


[[2 2 6 1 3]
 [9 6 1 0 1]
 [9 0 0 9 3]
 [4 0 0 4 1]
 [7 3 2 4 7]]


In [22]:
x = np.array([1, 0, 0, 0])
print(np.any(x))
x = np.array([0, 0, 0, 0])
print(np.any(x))


True
False


In [23]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(np.equal(x, y))
print(np.allclose(x, y))


[ True  True  True  True  True  True  True  True  True False]
True


In [24]:
nums = np.array([[3, 2, np.nan, 1], [10, 12, 10, 9], [5, np.nan, 1, np.nan]])
nums



array([[ 3.,  2., nan,  1.],
       [10., 12., 10.,  9.],
       [ 5., nan,  1., nan]])

In [25]:
print(np.isnan(nums))

[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [26]:
nums = np.array([[5.54, 3.38, 7.99], [3.54, 4.38, 6.99], [1.54, 2.39, 9.29]])
n = 6
print(nums[nums < n])


[5.54 3.38 3.54 4.38 1.54 2.39]


In [27]:
nums = np.array([[5.54, 3.38, 7.99], [3.54, 8.32, 6.99], [1.54, 2.39, 9.29]])
n = 8.32
r = 18.32
print(np.where(nums == n, r, nums))

[[ 5.54  3.38  7.99]
 [ 3.54 18.32  6.99]
 [ 1.54  2.39  9.29]]


In [28]:
print("\nReplace elements with of the said array which are less than", n, "with", r)
print(np.where(nums < n, r, nums))


Replace elements with of the said array which are less than 8.32 with 18.32
[[18.32 18.32 18.32]
 [18.32  8.32 18.32]
 [18.32 18.32  9.29]]


In [29]:
print("\nReplace elements with of the said array which are greater than", n, "with", r)
print(np.where(nums > n, r, nums))


Replace elements with of the said array which are greater than 8.32 with 18.32
[[ 5.54  3.38  7.99]
 [ 3.54  8.32  6.99]
 [ 1.54  2.39 18.32]]


In [30]:
nums1 = np.array([[2, 5, 2], [1, 5, 5]])
nums2 = np.array([[5, 3, 4], [3, 2, 5]])


In [31]:
print(nums1)

[[2 5 2]
 [1 5 5]]


In [32]:
print(nums2)

[[5 3 4]
 [3 2 5]]


In [33]:
print(np.multiply(nums1, nums2))

[[10 15  8]
 [ 3 10 25]]
